version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population_ethnicity_01H1BTK17GPDRRXWC0AW6Q8NS0:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition_ethnicity
      --output-dir output/01H1BTK17GPDRRXWC0AW6Q8NS0 --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/01H1BTK17GPDRRXWC0AW6Q8NS0/input_ethnicity.feather

  generate_study_population_weekly_01H1BTK17GPDRRXWC0AW6Q8NS0:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition
      --param codelist_1_frequency="weekly"
      --param breakdowns=""
      --index-date_range="2023-05-08 to 2023-05-08 by week"
      --output-dir=output/01H1BTK17GPDRRXWC0AW6Q8NS0
      --output-format=feather
      --output-file=output/01H1BTK17GPDRRXWC0AW6Q8NS0/input_weekly_2023-05-08.feather
    outputs:
      highly_sensitive:
        cohort: output/01H1BTK17GPDRRXWC0AW6Q8NS0/input_weekly_2023-05-08.feather

  generate_study_population_01H1BTK17GPDRRXWC0AW6Q8NS0:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition
      --index-date-range="2019-09-01 to 2023-04-30 by month"
      --output-dir=output/01H1BTK17GPDRRXWC0AW6Q8NS0
      --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/01H1BTK17GPDRRXWC0AW6Q8NS0/input_*.feather

  join_cohorts_01H1BTK17GPDRRXWC0AW6Q8NS0:
    run: >
      cohort-joiner:v0.0.38
        --lhs output/01H1BTK17GPDRRXWC0AW6Q8NS0/input_20*.feather
        --rhs output/01H1BTK17GPDRRXWC0AW6Q8NS0/input_ethnicity.feather
        --output-dir output/01H1BTK17GPDRRXWC0AW6Q8NS0/joined
    needs: [generate_study_population_01H1BTK17GPDRRXWC0AW6Q8NS0, generate_study_population_ethnicity_01H1BTK17GPDRRXWC0AW6Q8NS0]
    outputs:
      highly_sensitive:
        cohort: output/01H1BTK17GPDRRXWC0AW6Q8NS0/joined/input_20*.feather

  generate_measures_01H1BTK17GPDRRXWC0AW6Q8NS0:
    run: >
      python:latest -m analysis.measures
        --breakdowns=sex
        --breakdowns=age
        --breakdowns=ethnicity
        --breakdowns=imd
        --breakdowns=region
        --input-dir="output/01H1BTK17GPDRRXWC0AW6Q8NS0/joined"
        --output-dir="output/01H1BTK17GPDRRXWC0AW6Q8NS0"

    needs: [join_cohorts_01H1BTK17GPDRRXWC0AW6Q8NS0]
    outputs:
      moderately_sensitive:
        measure: output/01H1BTK17GPDRRXWC0AW6Q8NS0/measure_all.csv
        decile_measure: output/01H1BTK17GPDRRXWC0AW6Q8NS0/measure_practice_rate_deciles.csv

  top_5_table_01H1BTK17GPDRRXWC0AW6Q8NS0:
    run: >
      python:latest python analysis/top_5.py
      --codelist-1-path="interactive_codelists/codelist_1.csv"
      --codelist-2-path="interactive_codelists/codelist_2.csv"
      --output-dir="output/01H1BTK17GPDRRXWC0AW6Q8NS0"
    needs: [generate_measures_01H1BTK17GPDRRXWC0AW6Q8NS0]
    outputs:
      moderately_sensitive:
        table_1: output/01H1BTK17GPDRRXWC0AW6Q8NS0/top_5_code_table_1.csv
        table_2: output/01H1BTK17GPDRRXWC0AW6Q8NS0/top_5_code_table_2.csv
        tables_for_checking: output/01H1BTK17GPDRRXWC0AW6Q8NS0/for_checking/top_5*.csv

  plot_measure_01H1BTK17GPDRRXWC0AW6Q8NS0:
    run: >
      python:latest python analysis/plot_measures.py
        --breakdowns=sex
        --breakdowns=age
        --breakdowns=ethnicity
        --breakdowns=imd
        --breakdowns=region
        --input-dir output/01H1BTK17GPDRRXWC0AW6Q8NS0
        --output-dir output/01H1BTK17GPDRRXWC0AW6Q8NS0
    needs: [generate_measures_01H1BTK17GPDRRXWC0AW6Q8NS0]
    outputs:
      moderately_sensitive:
        measure: output/01H1BTK17GPDRRXWC0AW6Q8NS0/plot_measure*.png
        data: output/01H1BTK17GPDRRXWC0AW6Q8NS0/for_checking/plot_measure_for_checking.csv
        deciles: output/01H1BTK17GPDRRXWC0AW6Q8NS0/deciles_chart.png

  event_counts_01H1BTK17GPDRRXWC0AW6Q8NS0:
    run: >
      python:latest -m analysis.event_counts --input-dir="output/01H1BTK17GPDRRXWC0AW6Q8NS0" --output-dir="output/01H1BTK17GPDRRXWC0AW6Q8NS0"
    needs: [join_cohorts_01H1BTK17GPDRRXWC0AW6Q8NS0, generate_study_population_weekly_01H1BTK17GPDRRXWC0AW6Q8NS0]
    outputs:
      moderately_sensitive:
        measure: output/01H1BTK17GPDRRXWC0AW6Q8NS0/event_counts.json

  generate_report_01H1BTK17GPDRRXWC0AW6Q8NS0:
    run: >
      python:latest python analysis/render_report.py
      --output-dir="output/01H1BTK17GPDRRXWC0AW6Q8NS0"
    needs: [event_counts_01H1BTK17GPDRRXWC0AW6Q8NS0, top_5_table_01H1BTK17GPDRRXWC0AW6Q8NS0, plot_measure_01H1BTK17GPDRRXWC0AW6Q8NS0]
    outputs:
      moderately_sensitive:
        notebook: output/01H1BTK17GPDRRXWC0AW6Q8NS0/report.html