version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population_ethnicity_01GZP4S728BBX30GY1564BMDCN:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition_ethnicity
      --output-dir output/01GZP4S728BBX30GY1564BMDCN --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/01GZP4S728BBX30GY1564BMDCN/input_ethnicity.feather

  generate_study_population_weekly_01GZP4S728BBX30GY1564BMDCN:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition
      --param codelist_1_frequency="weekly"
      --param breakdowns=""
      --index-date_range="2023-04-17 to 2023-04-17 by week"
      --output-dir=output/01GZP4S728BBX30GY1564BMDCN
      --output-format=feather
      --output-file=output/01GZP4S728BBX30GY1564BMDCN/input_weekly_2023-04-17.feather
    outputs:
      highly_sensitive:
        cohort: output/01GZP4S728BBX30GY1564BMDCN/input_weekly_2023-04-17.feather

  generate_study_population_01GZP4S728BBX30GY1564BMDCN:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition
      --index-date-range="2019-09-01 to 2023-03-31 by month"
      --output-dir=output/01GZP4S728BBX30GY1564BMDCN
      --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/01GZP4S728BBX30GY1564BMDCN/input_*.feather

  join_cohorts_01GZP4S728BBX30GY1564BMDCN:
    run: >
      cohort-joiner:v0.0.38
        --lhs output/01GZP4S728BBX30GY1564BMDCN/input_20*.feather
        --rhs output/01GZP4S728BBX30GY1564BMDCN/input_ethnicity.feather
        --output-dir output/01GZP4S728BBX30GY1564BMDCN/joined
    needs: [generate_study_population_01GZP4S728BBX30GY1564BMDCN, generate_study_population_ethnicity_01GZP4S728BBX30GY1564BMDCN]
    outputs:
      highly_sensitive:
        cohort: output/01GZP4S728BBX30GY1564BMDCN/joined/input_20*.feather

  generate_measures_01GZP4S728BBX30GY1564BMDCN:
    run: >
      python:latest -m analysis.measures
        --breakdowns=sex
        --breakdowns=age
        --breakdowns=ethnicity
        --input-dir="output/01GZP4S728BBX30GY1564BMDCN/joined"

    needs: [join_cohorts_01GZP4S728BBX30GY1564BMDCN]
    outputs:
      moderately_sensitive:
        measure: output/01GZP4S728BBX30GY1564BMDCN/joined/measure_all.csv
        decile_measure: output/01GZP4S728BBX30GY1564BMDCN/joined/measure_practice_rate_deciles.csv

  top_5_table_01GZP4S728BBX30GY1564BMDCN:
    run: >
      python:latest python analysis/top_5.py
      --codelist-1-path="interactive_codelists/codelist_1.csv"
      --codelist-2-path="interactive_codelists/codelist_2.csv"
      --output-dir="output/01GZP4S728BBX30GY1564BMDCN"
    needs: [generate_measures_01GZP4S728BBX30GY1564BMDCN]
    outputs:
      moderately_sensitive:
        tables: output/01GZP4S728BBX30GY1564BMDCN/joined/top_5*.csv

  plot_measure_01GZP4S728BBX30GY1564BMDCN:
    run: >
      python:latest python analysis/plot_measures.py
        --breakdowns=sex
        --breakdowns=age
        --breakdowns=ethnicity
        --output-dir output/01GZP4S728BBX30GY1564BMDCN
    needs: [generate_measures_01GZP4S728BBX30GY1564BMDCN]
    outputs:
      moderately_sensitive:
        measure: output/01GZP4S728BBX30GY1564BMDCN/plot_measure*.png
        deciles: output/01GZP4S728BBX30GY1564BMDCN/deciles_chart.png

  event_counts_01GZP4S728BBX30GY1564BMDCN:
    run: >
      python:latest -m analysis.event_counts --input-dir="output/01GZP4S728BBX30GY1564BMDCN" --output-dir="output/01GZP4S728BBX30GY1564BMDCN"
    needs: [join_cohorts_01GZP4S728BBX30GY1564BMDCN, generate_study_population_weekly_01GZP4S728BBX30GY1564BMDCN]
    outputs:
      moderately_sensitive:
        measure: output/01GZP4S728BBX30GY1564BMDCN/event_counts.json

  generate_report_01GZP4S728BBX30GY1564BMDCN:
    run: >
      python:latest python analysis/render_report.py
      --output-dir="output/01GZP4S728BBX30GY1564BMDCN"
      --population="all"
      --breakdowns=sex
      --breakdowns=age
      --breakdowns=ethnicity
      --codelist-1-name="DMARDs"
      --codelist-2-name="Medication Review - OpenSAFELY Service Restoration Observatory"
      --codelist-1-link="opensafely/dmards/2020-06-23"
      --codelist-2-link="opensafely/medication-review-opensafely-service-restoration-observatory/24b50f64"
      --time-value="None"
      --time-scale=""
      --time-event="before"
      --start-date="2019-09-01"
      --end-date="2023-03-31"
      
      --time-ever
      
    needs: [event_counts_01GZP4S728BBX30GY1564BMDCN, top_5_table_01GZP4S728BBX30GY1564BMDCN, plot_measure_01GZP4S728BBX30GY1564BMDCN]
    outputs:
      moderately_sensitive:
        notebook: output/01GZP4S728BBX30GY1564BMDCN/report.html