version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population_ethnicity_01GYS9HN5T7FDEFW8F6V0TJ3CK:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition_ethnicity
      --param end_date="2023-03-31"
      --output-dir output/01GYS9HN5T7FDEFW8F6V0TJ3CK --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/01GYS9HN5T7FDEFW8F6V0TJ3CK/input_ethnicity.csv.gz

  generate_study_population_weekly_01GYS9HN5T7FDEFW8F6V0TJ3CK:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition
      --param codelist_1_path="interactive_codelists/codelist_1.csv"
      --param codelist_1_type="event"
      --param codelist_2_path="interactive_codelists/codelist_2.csv"
      --param codelist_2_type="medication"
      --param codelist_1_frequency="weekly"
      --param time_value="5"
      --param time_ever="False"
      --param time_scale="years"
      --param time_event="before"
      --param codelist_2_comparison_date="end_date"
      --param operator="AND"
      --param population="adults"
      --param breakdowns=""
      --index-date_range="2023-04-03 to 2023-04-03 by week"
      --output-dir=output/01GYS9HN5T7FDEFW8F6V0TJ3CK
      --output-format=csv.gz
      --output-file=output/01GYS9HN5T7FDEFW8F6V0TJ3CK/input_weekly_2023-04-03.csv.gz
    outputs:
      highly_sensitive:
        cohort: output/01GYS9HN5T7FDEFW8F6V0TJ3CK/input_weekly_2023-04-03.csv.gz

  generate_study_population_01GYS9HN5T7FDEFW8F6V0TJ3CK:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition
      --param codelist_1_path="interactive_codelists/codelist_1.csv"
      --param codelist_1_type="event"
      --param codelist_2_path="interactive_codelists/codelist_2.csv"
      --param codelist_2_type="medication"
      --param codelist_1_frequency="monthly"
      --param time_value="5"
      --param time_ever="False"
      --param time_scale="years"
      --param time_event="before"
      --param codelist_2_comparison_date="end_date"
      --param operator="AND"
      --param population="adults"
      --param breakdowns="sex,age"
      --index-date-range="2019-09-01 to 2023-03-31 by month"
      --output-dir=output/01GYS9HN5T7FDEFW8F6V0TJ3CK
      --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/01GYS9HN5T7FDEFW8F6V0TJ3CK/input_*.csv.gz

  join_cohorts_01GYS9HN5T7FDEFW8F6V0TJ3CK:
    run: >
      cohort-joiner:v0.0.38
        --lhs output/01GYS9HN5T7FDEFW8F6V0TJ3CK/input_20*.csv.gz
        --rhs output/01GYS9HN5T7FDEFW8F6V0TJ3CK/input_ethnicity.csv.gz
        --output-dir output/01GYS9HN5T7FDEFW8F6V0TJ3CK/joined
    needs: [generate_study_population_01GYS9HN5T7FDEFW8F6V0TJ3CK, generate_study_population_ethnicity_01GYS9HN5T7FDEFW8F6V0TJ3CK]
    outputs:
      highly_sensitive:
        cohort: output/01GYS9HN5T7FDEFW8F6V0TJ3CK/joined/input_20*.csv.gz

  generate_measures_01GYS9HN5T7FDEFW8F6V0TJ3CK:
    run: >
      python:latest -m analysis.measures
        --breakdowns=sex
        --breakdowns=age
        --input-dir="output/01GYS9HN5T7FDEFW8F6V0TJ3CK/joined"

    needs: [join_cohorts_01GYS9HN5T7FDEFW8F6V0TJ3CK]
    outputs:
      moderately_sensitive:
        measure: output/01GYS9HN5T7FDEFW8F6V0TJ3CK/joined/measure_all.csv
        decile_measure: output/01GYS9HN5T7FDEFW8F6V0TJ3CK/joined/measure_practice_rate_deciles.csv

  top_5_table_01GYS9HN5T7FDEFW8F6V0TJ3CK:
    run: >
      python:latest python analysis/top_5.py
      --codelist-1-path="interactive_codelists/codelist_1.csv"
      --codelist-2-path="interactive_codelists/codelist_2.csv"
      --output-dir="output/01GYS9HN5T7FDEFW8F6V0TJ3CK"
    needs: [generate_measures_01GYS9HN5T7FDEFW8F6V0TJ3CK]
    outputs:
      moderately_sensitive:
        tables: output/01GYS9HN5T7FDEFW8F6V0TJ3CK/joined/top_5*.csv

  plot_measure_01GYS9HN5T7FDEFW8F6V0TJ3CK:
    run: >
      python:latest python analysis/plot_measures.py
        --breakdowns=sex
        --breakdowns=age
        --output-dir output/01GYS9HN5T7FDEFW8F6V0TJ3CK
    needs: [generate_measures_01GYS9HN5T7FDEFW8F6V0TJ3CK]
    outputs:
      moderately_sensitive:
        measure: output/01GYS9HN5T7FDEFW8F6V0TJ3CK/plot_measure*.png
        deciles: output/01GYS9HN5T7FDEFW8F6V0TJ3CK/deciles_chart.png

  event_counts_01GYS9HN5T7FDEFW8F6V0TJ3CK:
    run: >
      python:latest python analysis/event_counts.py --input-dir="output/01GYS9HN5T7FDEFW8F6V0TJ3CK" --output-dir="output/01GYS9HN5T7FDEFW8F6V0TJ3CK"
    needs: [join_cohorts_01GYS9HN5T7FDEFW8F6V0TJ3CK, generate_study_population_weekly_01GYS9HN5T7FDEFW8F6V0TJ3CK]
    outputs:
      moderately_sensitive:
        measure: output/01GYS9HN5T7FDEFW8F6V0TJ3CK/event_counts.json

  generate_report_01GYS9HN5T7FDEFW8F6V0TJ3CK:
    run: >
      python:latest python analysis/render_report.py
      --output-dir="output/01GYS9HN5T7FDEFW8F6V0TJ3CK"
      --population="adults"
      --breakdowns=sex
      --breakdowns=age
      --codelist-1-name="Asthma annual review QOF"
      --codelist-2-name="Asthma Inhaler Salbutamol Medication"
      --codelist-1-link="opensafely/asthma-annual-review-qof/33eeb7da"
      --codelist-2-link="opensafely/asthma-inhaler-salbutamol-medication/2020-04-15"
      --time-value="5"
      --time-scale="years"
      --time-event="before"
      --start-date="2019-09-01"
      --end-date="2023-03-31"
    needs: [event_counts_01GYS9HN5T7FDEFW8F6V0TJ3CK, top_5_table_01GYS9HN5T7FDEFW8F6V0TJ3CK, plot_measure_01GYS9HN5T7FDEFW8F6V0TJ3CK]
    outputs:
      moderately_sensitive:
        notebook: output/01GYS9HN5T7FDEFW8F6V0TJ3CK/report.html