version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population_ethnicity_01GTCJBR19EXKC4V5X3CT389P2:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition_ethnicity
      --param end_date="2023-02-22"
      --output-dir output/01GTCJBR19EXKC4V5X3CT389P2 --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/01GTCJBR19EXKC4V5X3CT389P2/input_ethnicity.csv.gz


  generate_study_population_01GTCJBR19EXKC4V5X3CT389P2:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition
      --param codelist_1_path="codelists/codelist_1.csv"
      --param codelist_1_type="medication"
      --param codelist_2_path="codelists/codelist_2.csv"
      --param codelist_2_type="event"
      --param codelist_1_frequency="monthly"
      --param time_value="1"
      --param time_scale="years"
      --param time_event="before"
      --param codelist_2_comparison_date="event_1_date"
      --param operator="AND"
      --param population="adults"
      --param breakdowns="sex,age"
      --index-date-range="2019-09-01 to 2023-02-22 by month"
      --output-dir=output/01GTCJBR19EXKC4V5X3CT389P2
      --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/01GTCJBR19EXKC4V5X3CT389P2/input_*.csv.gz

  join_cohorts_01GTCJBR19EXKC4V5X3CT389P2:
    run: >
      cohort-joiner:v0.0.38
        --lhs output/01GTCJBR19EXKC4V5X3CT389P2/input_20*.csv.gz
        --rhs output/01GTCJBR19EXKC4V5X3CT389P2/input_ethnicity.csv.gz
        --output-dir output/01GTCJBR19EXKC4V5X3CT389P2/joined
    needs: [generate_study_population_01GTCJBR19EXKC4V5X3CT389P2, generate_study_population_ethnicity_01GTCJBR19EXKC4V5X3CT389P2]
    outputs:
      highly_sensitive:
        cohort: output/01GTCJBR19EXKC4V5X3CT389P2/joined/input_20*.csv.gz

  generate_measures_01GTCJBR19EXKC4V5X3CT389P2:
    run: >
      python:latest python analysis/measures.py
        --breakdowns="sex,age"
        --input_dir="output/01GTCJBR19EXKC4V5X3CT389P2/joined"
        --measure="med_review"

    needs: [join_cohorts_01GTCJBR19EXKC4V5X3CT389P2]
    outputs:
      moderately_sensitive:
        measure: output/01GTCJBR19EXKC4V5X3CT389P2/joined/measure*rate.csv
        decile_measure: output/01GTCJBR19EXKC4V5X3CT389P2/joined/measure*rate_deciles.csv

  top_5_table_01GTCJBR19EXKC4V5X3CT389P2:
    run: >
      python:latest python analysis/top_5.py
      --codelist-1-path="codelists/codelist_1.csv"
      --codelist-2-path="codelists/codelist_2.csv"
      --output-dir="output/01GTCJBR19EXKC4V5X3CT389P2"
    needs: [generate_measures_01GTCJBR19EXKC4V5X3CT389P2]
    outputs:
      moderately_sensitive:
        tables: output/01GTCJBR19EXKC4V5X3CT389P2/joined/top_5*.csv

  deciles_chart_01GTCJBR19EXKC4V5X3CT389P2:
    run: >
      deciles-charts:v0.0.33
        --input-files output/01GTCJBR19EXKC4V5X3CT389P2/joined/measure_practice_rate_deciles.csv
        --output-dir output/01GTCJBR19EXKC4V5X3CT389P2/joined
    config:
      show_outer_percentiles: true
      tables:
        output: true
      charts:
        output: true
    needs: [generate_measures_01GTCJBR19EXKC4V5X3CT389P2]
    outputs:
      moderately_sensitive:
        deciles_charts: output/01GTCJBR19EXKC4V5X3CT389P2/joined/deciles_*.*

  plot_measure_01GTCJBR19EXKC4V5X3CT389P2:
    run: >
      python:latest python analysis/plot_measures.py
        --breakdowns="sex,age"
        --output-dir output/01GTCJBR19EXKC4V5X3CT389P2
    needs: [generate_measures_01GTCJBR19EXKC4V5X3CT389P2]
    outputs:
      moderately_sensitive:
        measure: output/01GTCJBR19EXKC4V5X3CT389P2/plot_measure*.png

  event_counts_01GTCJBR19EXKC4V5X3CT389P2:
    run: >
      python:latest python analysis/event_counts.py --input_dir="output/01GTCJBR19EXKC4V5X3CT389P2/joined" --output_dir="output/01GTCJBR19EXKC4V5X3CT389P2"
    needs: [join_cohorts_01GTCJBR19EXKC4V5X3CT389P2]
    outputs:
      moderately_sensitive:
        measure: output/01GTCJBR19EXKC4V5X3CT389P2/event_counts.json

  create_notebook_01GTCJBR19EXKC4V5X3CT389P2:
    run: >
      python:latest python analysis/create_notebook.py
      --output-dir "output/01GTCJBR19EXKC4V5X3CT389P2"
      --codelist-1-description="None"
      --codelist-2-description="None"
      --codelist-1-link="https://codelists.opensafely.org/codelist/opensafely/dmards/2020-06-23"
      --codelist-2-link="https://codelists.opensafely.org/codelist/opensafely/medication-review-opensafely-service-restoration-observatory/24b50f64"
      --report-title="DMARDs & Medication Review - OpenSAFELY Service Restoration Observatory"
      --measure-description="Medication Review"
      --population="adults"
      --breakdowns="sex,age"
    outputs:
      moderately_sensitive:
        notebook: output/01GTCJBR19EXKC4V5X3CT389P2/report.ipynb

  generate_notebook_01GTCJBR19EXKC4V5X3CT389P2:
    run: jupyter:latest jupyter nbconvert /workspace/output/01GTCJBR19EXKC4V5X3CT389P2/report.ipynb --execute --to html --output-dir=/workspace/output/01GTCJBR19EXKC4V5X3CT389P2 --ExecutePreprocessor.timeout=86400 --no-input
    needs: [create_notebook_01GTCJBR19EXKC4V5X3CT389P2, event_counts_01GTCJBR19EXKC4V5X3CT389P2, deciles_chart_01GTCJBR19EXKC4V5X3CT389P2, top_5_table_01GTCJBR19EXKC4V5X3CT389P2, plot_measure_01GTCJBR19EXKC4V5X3CT389P2]
    outputs:
      moderately_sensitive:
        notebook: output/01GTCJBR19EXKC4V5X3CT389P2/report.html