version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population_ethnicity_01GYA0FM7C9PVSZAKS85ZBBZWX:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition_ethnicity
      --param end_date="2023-03-31"
      --output-dir output/01GYA0FM7C9PVSZAKS85ZBBZWX --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/01GYA0FM7C9PVSZAKS85ZBBZWX/input_ethnicity.csv.gz


  generate_study_population_01GYA0FM7C9PVSZAKS85ZBBZWX:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition
      --param codelist_1_path="interactive_codelists/codelist_1.csv"
      --param codelist_1_type="medication"
      --param codelist_2_path="interactive_codelists/codelist_2.csv"
      --param codelist_2_type="event"
      --param codelist_1_frequency="monthly"
      --param time_value="1"
      --param time_ever="False"
      --param time_scale="years"
      --param time_event="before"
      --param codelist_2_comparison_date="end_date"
      --param operator="AND"
      --param population="adults"
      --param breakdowns="sex,age,ethnicity"
      --index-date-range="2019-09-01 to 2023-03-31 by month"
      --output-dir=output/01GYA0FM7C9PVSZAKS85ZBBZWX
      --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/01GYA0FM7C9PVSZAKS85ZBBZWX/input_*.csv.gz

  join_cohorts_01GYA0FM7C9PVSZAKS85ZBBZWX:
    run: >
      cohort-joiner:v0.0.38
        --lhs output/01GYA0FM7C9PVSZAKS85ZBBZWX/input_20*.csv.gz
        --rhs output/01GYA0FM7C9PVSZAKS85ZBBZWX/input_ethnicity.csv.gz
        --output-dir output/01GYA0FM7C9PVSZAKS85ZBBZWX/joined
    needs: [generate_study_population_01GYA0FM7C9PVSZAKS85ZBBZWX, generate_study_population_ethnicity_01GYA0FM7C9PVSZAKS85ZBBZWX]
    outputs:
      highly_sensitive:
        cohort: output/01GYA0FM7C9PVSZAKS85ZBBZWX/joined/input_20*.csv.gz

  generate_measures_01GYA0FM7C9PVSZAKS85ZBBZWX:
    run: >
      python:latest -m analysis.measures
        --breakdowns="sex,age,ethnicity"
        --input_dir="output/01GYA0FM7C9PVSZAKS85ZBBZWX/joined"

    needs: [join_cohorts_01GYA0FM7C9PVSZAKS85ZBBZWX]
    outputs:
      moderately_sensitive:
        measure: output/01GYA0FM7C9PVSZAKS85ZBBZWX/joined/measure_all.csv
        decile_measure: output/01GYA0FM7C9PVSZAKS85ZBBZWX/joined/measure_practice_rate_deciles.csv

  top_5_table_01GYA0FM7C9PVSZAKS85ZBBZWX:
    run: >
      python:latest python analysis/top_5.py
      --codelist-1-path="interactive_codelists/codelist_1.csv"
      --codelist-2-path="interactive_codelists/codelist_2.csv"
      --output-dir="output/01GYA0FM7C9PVSZAKS85ZBBZWX"
    needs: [generate_measures_01GYA0FM7C9PVSZAKS85ZBBZWX]
    outputs:
      moderately_sensitive:
        tables: output/01GYA0FM7C9PVSZAKS85ZBBZWX/joined/top_5*.csv

  plot_measure_01GYA0FM7C9PVSZAKS85ZBBZWX:
    run: >
      python:latest python analysis/plot_measures.py
        --breakdowns="sex,age,ethnicity"
        --output-dir output/01GYA0FM7C9PVSZAKS85ZBBZWX
    needs: [generate_measures_01GYA0FM7C9PVSZAKS85ZBBZWX]
    outputs:
      moderately_sensitive:
        measure: output/01GYA0FM7C9PVSZAKS85ZBBZWX/plot_measure*.png
        deciles: output/01GYA0FM7C9PVSZAKS85ZBBZWX/deciles_chart.png

  event_counts_01GYA0FM7C9PVSZAKS85ZBBZWX:
    run: >
      python:latest python analysis/event_counts.py --input_dir="output/01GYA0FM7C9PVSZAKS85ZBBZWX/joined" --output_dir="output/01GYA0FM7C9PVSZAKS85ZBBZWX"
    needs: [join_cohorts_01GYA0FM7C9PVSZAKS85ZBBZWX]
    outputs:
      moderately_sensitive:
        measure: output/01GYA0FM7C9PVSZAKS85ZBBZWX/event_counts.json

  generate_report_01GYA0FM7C9PVSZAKS85ZBBZWX:
    run: >
      python:latest python analysis/render_report.py
      --output-dir="output/01GYA0FM7C9PVSZAKS85ZBBZWX"
      --population="adults"
      --breakdowns="sex,age,ethnicity"
      --codelist-1-name="DMARDs"
      --codelist-2-name="Care planning medication review simple reference set - NHS Digital"
      --codelist-1-link="opensafely/dmards/2020-06-23"
      --codelist-2-link="opensafely/care-planning-medication-review-simple-reference-set-nhs-digital/61b13c39"
      --time-value="1"
      --time-scale="years"
      --time-event="before"
      --start-date="2019-09-01"
      --end-date="2023-03-31"
    needs: [event_counts_01GYA0FM7C9PVSZAKS85ZBBZWX, top_5_table_01GYA0FM7C9PVSZAKS85ZBBZWX, plot_measure_01GYA0FM7C9PVSZAKS85ZBBZWX]
    outputs:
      moderately_sensitive:
        notebook: output/01GYA0FM7C9PVSZAKS85ZBBZWX/report.html