version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population_ethnicity_01H0T8ZY6V6QJR5DBFMDK45DV7:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition_ethnicity
      --output-dir output/01H0T8ZY6V6QJR5DBFMDK45DV7 --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/01H0T8ZY6V6QJR5DBFMDK45DV7/input_ethnicity.feather

  generate_study_population_weekly_01H0T8ZY6V6QJR5DBFMDK45DV7:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition
      --param codelist_1_frequency="weekly"
      --param breakdowns=""
      --index-date_range="2023-05-01 to 2023-05-01 by week"
      --output-dir=output/01H0T8ZY6V6QJR5DBFMDK45DV7
      --output-format=feather
      --output-file=output/01H0T8ZY6V6QJR5DBFMDK45DV7/input_weekly_2023-05-01.feather
    outputs:
      highly_sensitive:
        cohort: output/01H0T8ZY6V6QJR5DBFMDK45DV7/input_weekly_2023-05-01.feather

  generate_study_population_01H0T8ZY6V6QJR5DBFMDK45DV7:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition
      --index-date-range="2019-09-01 to 2023-04-30 by month"
      --output-dir=output/01H0T8ZY6V6QJR5DBFMDK45DV7
      --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/01H0T8ZY6V6QJR5DBFMDK45DV7/input_*.feather

  join_cohorts_01H0T8ZY6V6QJR5DBFMDK45DV7:
    run: >
      cohort-joiner:v0.0.38
        --lhs output/01H0T8ZY6V6QJR5DBFMDK45DV7/input_20*.feather
        --rhs output/01H0T8ZY6V6QJR5DBFMDK45DV7/input_ethnicity.feather
        --output-dir output/01H0T8ZY6V6QJR5DBFMDK45DV7/joined
    needs: [generate_study_population_01H0T8ZY6V6QJR5DBFMDK45DV7, generate_study_population_ethnicity_01H0T8ZY6V6QJR5DBFMDK45DV7]
    outputs:
      highly_sensitive:
        cohort: output/01H0T8ZY6V6QJR5DBFMDK45DV7/joined/input_20*.feather

  generate_measures_01H0T8ZY6V6QJR5DBFMDK45DV7:
    run: >
      python:latest -m analysis.measures
        --breakdowns=sex
        --breakdowns=age
        --breakdowns=ethnicity
        --breakdowns=imd
        --breakdowns=region
        --input-dir="output/01H0T8ZY6V6QJR5DBFMDK45DV7/joined"

    needs: [join_cohorts_01H0T8ZY6V6QJR5DBFMDK45DV7]
    outputs:
      moderately_sensitive:
        measure: output/01H0T8ZY6V6QJR5DBFMDK45DV7/joined/measure_all.csv
        decile_measure: output/01H0T8ZY6V6QJR5DBFMDK45DV7/joined/measure_practice_rate_deciles.csv

  top_5_table_01H0T8ZY6V6QJR5DBFMDK45DV7:
    run: >
      python:latest python analysis/top_5.py
      --codelist-1-path="interactive_codelists/codelist_1.csv"
      --codelist-2-path="interactive_codelists/codelist_2.csv"
      --output-dir="output/01H0T8ZY6V6QJR5DBFMDK45DV7"
    needs: [generate_measures_01H0T8ZY6V6QJR5DBFMDK45DV7]
    outputs:
      moderately_sensitive:
        tables: output/01H0T8ZY6V6QJR5DBFMDK45DV7/joined/top_5*.csv

  plot_measure_01H0T8ZY6V6QJR5DBFMDK45DV7:
    run: >
      python:latest python analysis/plot_measures.py
        --breakdowns=sex
        --breakdowns=age
        --breakdowns=ethnicity
        --breakdowns=imd
        --breakdowns=region
        --output-dir output/01H0T8ZY6V6QJR5DBFMDK45DV7
    needs: [generate_measures_01H0T8ZY6V6QJR5DBFMDK45DV7]
    outputs:
      moderately_sensitive:
        measure: output/01H0T8ZY6V6QJR5DBFMDK45DV7/plot_measure*.png
        deciles: output/01H0T8ZY6V6QJR5DBFMDK45DV7/deciles_chart.png

  event_counts_01H0T8ZY6V6QJR5DBFMDK45DV7:
    run: >
      python:latest -m analysis.event_counts --input-dir="output/01H0T8ZY6V6QJR5DBFMDK45DV7" --output-dir="output/01H0T8ZY6V6QJR5DBFMDK45DV7"
    needs: [join_cohorts_01H0T8ZY6V6QJR5DBFMDK45DV7, generate_study_population_weekly_01H0T8ZY6V6QJR5DBFMDK45DV7]
    outputs:
      moderately_sensitive:
        measure: output/01H0T8ZY6V6QJR5DBFMDK45DV7/event_counts.json

  generate_report_01H0T8ZY6V6QJR5DBFMDK45DV7:
    run: >
      python:latest python analysis/render_report.py
      --output-dir="output/01H0T8ZY6V6QJR5DBFMDK45DV7"
    needs: [event_counts_01H0T8ZY6V6QJR5DBFMDK45DV7, top_5_table_01H0T8ZY6V6QJR5DBFMDK45DV7, plot_measure_01H0T8ZY6V6QJR5DBFMDK45DV7]
    outputs:
      moderately_sensitive:
        notebook: output/01H0T8ZY6V6QJR5DBFMDK45DV7/report.html