version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population_ethnicity_01GXQX2XHHW4CFQ3TMH3S0NJ7J:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition_ethnicity
      --param end_date="2023-04-05"
      --output-dir output/01GXQX2XHHW4CFQ3TMH3S0NJ7J --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/01GXQX2XHHW4CFQ3TMH3S0NJ7J/input_ethnicity.csv.gz


  generate_study_population_01GXQX2XHHW4CFQ3TMH3S0NJ7J:
    run: cohortextractor:latest generate_cohort
      --study-definition study_definition
      --param codelist_1_path="interactive_codelists/codelist_1.csv"
      --param codelist_1_type="medication"
      --param codelist_2_path="interactive_codelists/codelist_2.csv"
      --param codelist_2_type="event"
      --param codelist_1_frequency="monthly"
      --param time_value="5"
      --param time_scale="years"
      --param time_event="before"
      --param codelist_2_comparison_date="end_date"
      --param operator="AND"
      --param population="children"
      --param breakdowns="age,imd,region,ethnicity,sex"
      --index-date-range="2019-09-01 to 2023-04-05 by month"
      --output-dir=output/01GXQX2XHHW4CFQ3TMH3S0NJ7J
      --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/01GXQX2XHHW4CFQ3TMH3S0NJ7J/input_*.csv.gz

  join_cohorts_01GXQX2XHHW4CFQ3TMH3S0NJ7J:
    run: >
      cohort-joiner:v0.0.38
        --lhs output/01GXQX2XHHW4CFQ3TMH3S0NJ7J/input_20*.csv.gz
        --rhs output/01GXQX2XHHW4CFQ3TMH3S0NJ7J/input_ethnicity.csv.gz
        --output-dir output/01GXQX2XHHW4CFQ3TMH3S0NJ7J/joined
    needs: [generate_study_population_01GXQX2XHHW4CFQ3TMH3S0NJ7J, generate_study_population_ethnicity_01GXQX2XHHW4CFQ3TMH3S0NJ7J]
    outputs:
      highly_sensitive:
        cohort: output/01GXQX2XHHW4CFQ3TMH3S0NJ7J/joined/input_20*.csv.gz

  generate_measures_01GXQX2XHHW4CFQ3TMH3S0NJ7J:
    run: >
      python:latest -m analysis.measures
        --breakdowns="age,imd,region,ethnicity,sex"
        --input_dir="output/01GXQX2XHHW4CFQ3TMH3S0NJ7J/joined"
        --measure="med_review"

    needs: [join_cohorts_01GXQX2XHHW4CFQ3TMH3S0NJ7J]
    outputs:
      moderately_sensitive:
        measure: output/01GXQX2XHHW4CFQ3TMH3S0NJ7J/joined/measure*rate.csv
        decile_measure: output/01GXQX2XHHW4CFQ3TMH3S0NJ7J/joined/measure*rate_deciles.csv

  top_5_table_01GXQX2XHHW4CFQ3TMH3S0NJ7J:
    run: >
      python:latest python analysis/top_5.py
      --codelist-1-path="interactive_codelists/codelist_1.csv"
      --codelist-2-path="interactive_codelists/codelist_2.csv"
      --output-dir="output/01GXQX2XHHW4CFQ3TMH3S0NJ7J"
    needs: [generate_measures_01GXQX2XHHW4CFQ3TMH3S0NJ7J]
    outputs:
      moderately_sensitive:
        tables: output/01GXQX2XHHW4CFQ3TMH3S0NJ7J/joined/top_5*.csv

  deciles_chart_01GXQX2XHHW4CFQ3TMH3S0NJ7J:
    run: >
      deciles-charts:v0.0.33
        --input-files output/01GXQX2XHHW4CFQ3TMH3S0NJ7J/joined/measure_practice_rate_deciles.csv
        --output-dir output/01GXQX2XHHW4CFQ3TMH3S0NJ7J/joined
    config:
      show_outer_percentiles: true
      tables:
        output: true
      charts:
        output: true
    needs: [generate_measures_01GXQX2XHHW4CFQ3TMH3S0NJ7J]
    outputs:
      moderately_sensitive:
        deciles_charts: output/01GXQX2XHHW4CFQ3TMH3S0NJ7J/joined/deciles_*.*

  plot_measure_01GXQX2XHHW4CFQ3TMH3S0NJ7J:
    run: >
      python:latest python analysis/plot_measures.py
        --breakdowns="age,imd,region,ethnicity,sex"
        --output-dir output/01GXQX2XHHW4CFQ3TMH3S0NJ7J
    needs: [generate_measures_01GXQX2XHHW4CFQ3TMH3S0NJ7J]
    outputs:
      moderately_sensitive:
        measure: output/01GXQX2XHHW4CFQ3TMH3S0NJ7J/plot_measure*.png

  event_counts_01GXQX2XHHW4CFQ3TMH3S0NJ7J:
    run: >
      python:latest python analysis/event_counts.py --input_dir="output/01GXQX2XHHW4CFQ3TMH3S0NJ7J/joined" --output_dir="output/01GXQX2XHHW4CFQ3TMH3S0NJ7J"
    needs: [join_cohorts_01GXQX2XHHW4CFQ3TMH3S0NJ7J]
    outputs:
      moderately_sensitive:
        measure: output/01GXQX2XHHW4CFQ3TMH3S0NJ7J/event_counts.json

  generate_report_01GXQX2XHHW4CFQ3TMH3S0NJ7J:
    run: >
      python:latest python analysis/render_report.py
      --output-dir="output/01GXQX2XHHW4CFQ3TMH3S0NJ7J"
      --report-title="Asthma Inhaler Salbutamol Medication & Asthma Diagnosis code"
      --population="children"
      --breakdowns="age,imd,region,ethnicity,sex"
      --codelist-1-name="Asthma Inhaler Salbutamol Medication"
      --codelist-2-name="Asthma Diagnosis code"
      --codelist-1-link="opensafely/asthma-inhaler-salbutamol-medication/2020-04-15"
      --codelist-2-link="primis-covid19-vacc-uptake/ast/v.1.5.3"
      --time-value="5"
      --time-scale="years"
      --time-event="before"
      --start-date="2019-09-01"
      --end-date="2023-04-05"
    needs: [event_counts_01GXQX2XHHW4CFQ3TMH3S0NJ7J, deciles_chart_01GXQX2XHHW4CFQ3TMH3S0NJ7J, top_5_table_01GXQX2XHHW4CFQ3TMH3S0NJ7J, plot_measure_01GXQX2XHHW4CFQ3TMH3S0NJ7J]
    outputs:
      moderately_sensitive:
        notebook: output/01GXQX2XHHW4CFQ3TMH3S0NJ7J/report.html